export const MOVIES_LOADING = "MOVIES_LOADING";
export const MOVIES_LOAD_SUCCESS = "MOVIES_LOAD_SUCCESS";
export const CAROUSEL_MOVIES_LOAD_SUCCESS = "CAROUSEL_MOVIES_LOAD_SUCCESS";
export const MOVIE_LOAD_SUCCESS = "MOVIE_LOAD_SUCCESS";
export const MOVIES_SEARCH_SUCCESS = "MOVIES_SEARCH_SUCCESS";
export const MOVIES_SEARCH_BUTTON_SUCCESS = "MOVIES_SEARCH_BUTTON_SUCCESS";
export const MOVIES_LOAD_ERROR = "MOVIES_LOAD_ERROR";
